# Production-specific Docker Compose overrides
version: '3.8'

services:
  app:
    environment:
      - APP_DEBUG=false
      - APP_ENV=production
      - LOG_LEVEL=WARNING
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  worker:
    environment:
      - APP_ENV=production
      - LOG_LEVEL=WARNING
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    restart: always
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  nginx:
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"